version: '2'
services:
  postgres:
    image: postgres:9.5.3
    ports:
      - "5432"
  web:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.development
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "80:3000"
    depends_on:
      - postgres
    volumes_from:
      - bundle_cache
    environment:
      - OP_CLIENT_ID
      - OP_SECRET_KEY
      - OP_CALLBACK_URL=http://dev.interoperabilidad.digital.gob.cl
      - ROLLBAR_ACCESS_TOKEN
  bundle_cache:
    image: ruby:2.3.1 # Should be the same as the app Dockerfile.dev base image
    volumes:
      - /usr/local/bundle
